### PR TITLE
updating url for poland for SSL

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
there seems to be a problem with their cert

**Comment by radius314** [comment]
which url?

**Comment by pjaudiomv** [comment]
ahh nm, nothing to see here.

**Comment by pjaudiomv** [comment]
didnt see url changed, looks good

**Comment by jbraswell** [comment]
Their cert with the new URL looks fine to me. What is the problem you’re seeing?

**Pull request merged**
