### PR TITLE
add Western States Zonal Forum, delete Washington Northern Idaho Region

### PR DESCRIPTION
**Pull request by alanborning**

### CODE REVIEW

**Comment by jbraswell** [comment]
Is there anything out there that depends on WNIR's service body ids? Because when you change the id of the root server in tomato, it's going to purge all the data before re-importing, and the ids will change.

**Comment by alanborning** [comment]
As far as I know, the only thing that depends on this is an experimental display of all the meetings in the zone.  To avoid any downtime for Seattle I'm going to switch it back to using the region's server until the dust settles.

**Comment by jbraswell** [comment]
Okay - so you're comfortable with me merging this?

**Comment by alanborning** [comment]
yes, please go ahead!

**Pull request merged**
