### PR TITLE
temp import for wsld, ignore all SBs except pacific/cascade and washi…

### PR DESCRIPTION
**Pull request by pjaudiomv**
…ngton/northern idaho region

### CODE REVIEW

**Comment by radius314** [comment]
for the people

**Comment by pjaudiomv** [comment]
obtained the list with this mess

```php
$serviceBodies = json_decode(file_get_contents("https://wsld.bmltenabled.org/main_server/client_interface/json/?switcher=GetServiceBodies"), true);

foreach ($serviceBodies as $serviceBody) {
  if ($serviceBody['parent_id'] != '1' && $serviceBody['id'] != '1' && $serviceBody['parent_id'] != '21' && $serviceBody['id'] != '21') {
    echo $serviceBody['id'];
    echo ", ";
  }
}
```

**Comment by radius314** [comment]
what list?

**Comment by pjaudiomv** [comment]
my b the ignore list https://github.com/bmlt-enabled/tomato/pull/64/files#diff-9a92f77a5988673ab2ae0be08b8a6374R202

**Comment by pjaudiomv** [comment]
maybe i should add northern california too and just ignore san fran

**Comment by radius314** [comment]
lgtm

**Pull request merged**
