### PR TITLE
change polish server url

### PR DESCRIPTION
**Pull request by pjaudiomv**

### CODE REVIEW

**Comment by jbraswell** [comment]
@alanb2718 should we merge this?

**Comment by alanb2718** [comment]
It's certainly not our place to tell people how to run their servers, but I'd suggest getting a little more information first.  The new URL is for a server running version 2.14.4!  That sure doesn't seem good -- they used to be on 2.15.6 according to the tally.

**Comment by alanb2718** [comment]
The root server changelog says that version 2.14.4 included adding Polish formats -- this is very likely connected with their using that version.  But if they are willing, we should help them migrate to the current version.

**Comment by jbraswell** [comment]
Yes, let's get them upgraded

**Pull request merged**
